import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('gu'));
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'VyaparMitra',
      'app_tagline': 'Local AI Voice Assistant for Business',
      'select_language': 'Select Language',
      'choose_preferred_language': 'Choose your preferred language for the app',
      'continue_btn': 'Continue',
      'home': 'Home',
      'history': 'History',
      'settings': 'Settings',
      'voice_record': 'Record Voice',
      'todays_pending': 'Today\'s Pending Tasks',
      'total_pending_amount': 'Total Pending Balance',
      'recent_tasks': 'Recent Business Tasks',
      'view_all': 'View All',
      'no_recent_tasks': 'No recent tasks yet. Tap record to add one.',
      'no_history': 'No history yet. Record your first business instruction.',
      'listening': 'Listening to your voice...',
      'tap_to_speak': 'Tap microphone to speak',
      'tap_to_stop': 'Tap to stop recording',
      'processing_ai': 'Understanding your instruction...',
      'step_speech': 'Recognizing voice instruction...',
      'step_ai': 'Extracting customer, task & payment details via local Gemma AI...',
      'step_task': 'Preparing structured task card...',
      'edit_task': 'Verify & Edit Task',
      'customer_name': 'Customer Name',
      'instruction_type': 'Instruction Type',
      'action': 'Action / Work',
      'item_name': 'Item / Goods Name',
      'quantity': 'Quantity',
      'quantity_unit': 'Unit (e.g. box, kg, pcs)',
      'amount': 'Amount (₹)',
      'due_date': 'Due Date',
      'due_time': 'Due Time',
      'payment_status': 'Payment Status',
      'task_status': 'Task Status',
      'next_action': 'Next Action',
      'notes': 'Notes / Remarks',
      'save_task': 'Save Task & Generate Message',
      'whatsapp_message': 'WhatsApp Message',
      'copy': 'Copy',
      'share': 'Share',
      'speak': 'Speak',
      'stop': 'Stop',
      'regenerate': 'Regenerate',
      'low_confidence_warning': 'Please check details. AI confidence is low.',
      'pending': 'Pending',
      'paid': 'Paid',
      'completed': 'Completed',
      'in_progress': 'In Progress',
      'cancelled': 'Cancelled',
      'partial': 'Partial',
      'not_applicable': 'N/A',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'earlier_this_week': 'Earlier this week',
      'last_week': 'Last week',
      'older': 'Older',
      'search_placeholder': 'Search by customer, item, action...',
      'all': 'All',
      'filter_all': 'All',
      'filter_pending': 'Pending',
      'filter_completed': 'Completed',
      'ollama_server': 'Ollama Base URL',
      'gemma_model': 'Gemma Model Tag',
      'test_connection': 'Test Connection',
      'connection_successful': 'Successfully connected to Ollama server!',
      'connection_failed': 'Could not connect to Ollama. Verify server URL.',
      'mic_permission_denied': 'Microphone permission is required to listen.',
      'speech_not_available': 'Speech recognition is not available on this device.',
      'gemma_error': 'Gemma model could not be reached. Ensure Ollama is running on your PC and server IP is reachable.',
      'retry': 'Retry',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'delete_confirm_title': 'Delete Task?',
      'delete_confirm_msg': 'Are you sure you want to delete this task from history?',
      'saved_successfully': 'Task saved successfully!',
      'message_copied': 'Message copied to clipboard!',
      'app_info': 'VyaparMitra AI • Offline Local Assistant',
      'version': 'Version 1.0.0',
    },
    'gu': {
      'app_name': 'વેપારમિત્ર',
      'app_tagline': 'વ્યવસાય માટે લોકલ AI અવાજ સહાયક',
      'select_language': 'ભાષા પસંદ કરો',
      'choose_preferred_language': 'એપ્લિકેશન માટે તમારી પસંદગીની ભાષા પસંદ કરો',
      'continue_btn': 'આગળ વધો',
      'home': 'હોમ',
      'history': 'ઇતિહાસ',
      'settings': 'સેટિંગ્સ',
      'voice_record': 'અવાજ રેકોર્ડ કરો',
      'todays_pending': 'આજના બાકી કામો',
      'total_pending_amount': 'કુલ બાકી રકમ',
      'recent_tasks': 'તાજેતરના વ્યવસાયિક કામો',
      'view_all': 'બધું જુઓ',
      'no_recent_tasks': 'હજી સુધી કોઈ તાજેતરના કામો નથી. નવું ઉમેરવા માટે રેકોર્ડ પર ટેપ કરો.',
      'no_history': 'હજી કોઈ ઇતિહાસ નથી. તમારી પ્રથમ વ્યવસાયિક સૂચના રેકોર્ડ કરો.',
      'listening': 'તમારો અવાજ સાંભળી રહ્યા છીએ...',
      'tap_to_speak': 'બોલવા માટે માઇક્રોફોન પર ટેપ કરો',
      'tap_to_stop': 'રેકોર્ડિંગ બંધ કરવા ટેપ કરો',
      'processing_ai': 'તમારી સૂચના સમજી રહ્યા છીએ...',
      'step_speech': 'અવાજ સૂચના ઓળખી રહ્યા છીએ...',
      'step_ai': 'લોકલ Gemma AI દ્વારા ગ્રાહક, કામ અને ચુકવણી વિગતો કાઢી રહ્યા છીએ...',
      'step_task': 'સ્ટ્રક્ચર્ડ ટાસ્ક કાર્ડ તૈયાર કરી રહ્યા છીએ...',
      'edit_task': 'વિગતો ચકાસો અને ફેરફાર કરો',
      'customer_name': 'ગ્રાહકનું નામ',
      'instruction_type': 'સૂચનાનો પ્રકાર',
      'action': 'કાર્ય / કામગીરી',
      'item_name': 'વસ્તુ / માલનું નામ',
      'quantity': 'જથ્થો (નંગ/બોક્સ)',
      'quantity_unit': 'એકમ (દા.ત. બોક્સ, કિલો, નંગ)',
      'amount': 'રકમ (₹)',
      'due_date': 'તારીખ',
      'due_time': 'સમય',
      'payment_status': 'ચુકવણી સ્થિતિ',
      'task_status': 'કામની સ્થિતિ',
      'next_action': 'આગામી પગલું',
      'notes': 'નોંધ / વિગત',
      'save_task': 'ટાસ્ક સાચવો અને મેસેજ બનાવો',
      'whatsapp_message': 'વોટ્સએપ મેસેજ',
      'copy': 'કોપી કરો',
      'share': 'શેર કરો',
      'speak': 'સાંભળો',
      'stop': 'બંધ કરો',
      'regenerate': 'ફરી બનાવો',
      'low_confidence_warning': 'કૃપા કરીને વિગતો ચકાસો. AI ખાતરી ઓછી છે.',
      'pending': 'બાકી',
      'paid': 'ચુકવેલ',
      'completed': 'પૂર્ણ',
      'in_progress': 'પ્રગતિમાં',
      'cancelled': 'રદ કરેલ',
      'partial': 'અંશતઃ',
      'not_applicable': 'લાગુ નથી',
      'today': 'આજે',
      'yesterday': 'ગઈકાલે',
      'earlier_this_week': 'આ સપ્તાહમાં',
      'last_week': 'ગયા સપ્તાહમાં',
      'older': 'જૂનું',
      'search_placeholder': 'ગ્રાહક, વસ્તુ અથવા કામ શોધો...',
      'all': 'બધા',
      'filter_all': 'બધા',
      'filter_pending': 'બાકી',
      'filter_completed': 'પૂર્ણ',
      'ollama_server': 'Ollama સર્વર સરનામું',
      'gemma_model': 'Gemma મોડલ નામ',
      'test_connection': 'કનેક્શન ચકાસો',
      'connection_successful': 'Ollama સર્વર સાથે સફળતાપૂર્વક કનેક્ટ થયું!',
      'connection_failed': 'Ollama સાથે કનેક્ટ થઈ શક્યું નથી. URL ચકાસો.',
      'mic_permission_denied': 'સાંભળવા માટે માઇક્રોફોનની મંજૂરી જરૂરી છે.',
      'speech_not_available': 'આ ઉપકરણ પર અવાજ ઓળખ ઉપલબ્ધ નથી.',
      'gemma_error': 'Gemma મોડલ સુધી પહોંચી શકાયું નથી. તમારા PC પર Ollama ચાલુ છે તેની ખાતરી કરો.',
      'retry': 'ફરી પ્રયાસ કરો',
      'delete': 'ડીલીટ',
      'cancel': 'રદ કરો',
      'delete_confirm_title': 'ટાસ્ક ડીલીટ કરવો છે?',
      'delete_confirm_msg': 'શું તમે ખરેખર આ ટાસ્ક ઇતિહાસમાંથી ડીલીટ કરવા માંગો છો?',
      'saved_successfully': 'ટાસ્ક સફળતાપૂર્વક સાચવવામાં આવ્યો!',
      'message_copied': 'મેસેજ કોપી થયો!',
      'app_info': 'વેપારમિત્ર AI • ઑફલાઇન લોકલ મદદગાર',
      'version': 'આવૃત્તિ 1.0.0',
    },
    'hi': {
      'app_name': 'व्यापारमित्र',
      'app_tagline': 'व्यापार के लिए लोकल AI वॉयस असिस्टेंट',
      'select_language': 'भाषा चुनें',
      'choose_preferred_language': 'ऐप के लिए अपनी पसंदीदा भाषा चुनें',
      'continue_btn': 'आगे बढ़ें',
      'home': 'होम',
      'history': 'इतिहास',
      'settings': 'सेटिंग्स',
      'voice_record': 'आवाज रिकॉर्ड करें',
      'todays_pending': 'आज के बाकी काम',
      'total_pending_amount': 'कुल बाकी राशि',
      'recent_tasks': 'हाल के व्यावसायिक काम',
      'view_all': 'सभी देखें',
      'no_recent_tasks': 'अभी कोई काम नहीं है। नया जोड़ने के लिए रिकॉर्ड पर टैप करें।',
      'no_history': 'अभी कोई इतिहास नहीं है। अपना पहला निर्देश रिकॉर्ड करें।',
      'listening': 'आपकी आवाज सुन रहे हैं...',
      'tap_to_speak': 'बोलने के लिए माइक पर टैप करें',
      'tap_to_stop': 'रिकॉर्डिंग रोकने के लिए टैप करें',
      'processing_ai': 'आपका निर्देश समझ रहे हैं...',
      'step_speech': 'आवाज निर्देश की पहचान की जा रही है...',
      'step_ai': 'लोकल Gemma AI द्वारा ग्राहक, कार्य और भुगतान विवरण निकाला जा रहा है...',
      'step_task': 'टास्क कार्ड तैयार किया जा रहा है...',
      'edit_task': 'विवरण जांचें और बदलें',
      'customer_name': 'ग्राहक का नाम',
      'instruction_type': 'निर्देश का प्रकार',
      'action': 'कार्य / काम',
      'item_name': 'सामान / माल का नाम',
      'quantity': 'मात्रा',
      'quantity_unit': 'इकाई (जैसे बॉक्स, किलो, पीस)',
      'amount': 'राशि (₹)',
      'due_date': 'तारीख',
      'due_time': 'समय',
      'payment_status': 'भुगतान स्थिति',
      'task_status': 'कार्य स्थिति',
      'next_action': 'अगला कदम',
      'notes': 'टिप्पणी / विवरण',
      'save_task': 'टास्क सेव करें और मैसेज बनाएं',
      'whatsapp_message': 'व्हाट्सएप मैसेज',
      'copy': 'कॉपी करें',
      'share': 'शेयर करें',
      'speak': 'सुनें',
      'stop': 'रोकें',
      'regenerate': 'पुनः बनाएं',
      'low_confidence_warning': 'कृपया विवरण जांचें। AI का अनुमान अनिश्चित है।',
      'pending': 'बाकी',
      'paid': 'भुगतान किया',
      'completed': 'पूरा हुआ',
      'in_progress': 'जारी है',
      'cancelled': 'रद्द',
      'partial': 'आंशिक',
      'not_applicable': 'लागू नहीं',
      'today': 'आज',
      'yesterday': 'कल',
      'earlier_this_week': 'इस सप्ताह',
      'last_week': 'पिछले सप्ताह',
      'older': 'पुराना',
      'search_placeholder': 'ग्राहक, सामान या काम खोजें...',
      'all': 'सभी',
      'filter_all': 'सभी',
      'filter_pending': 'बाकी',
      'filter_completed': 'पूरा',
      'ollama_server': 'Ollama सर्वर पता',
      'gemma_model': 'Gemma मॉडल का नाम',
      'test_connection': 'कनेक्शन जांचें',
      'connection_successful': 'Ollama सर्वर से सफलतापूर्वक कनेक्ट हो गया!',
      'connection_failed': 'Ollama से कनेक्ट नहीं हो सका। URL जांचें।',
      'mic_permission_denied': 'सुनने के लिए माइक्रोफ़ोन की अनुमति आवश्यक है।',
      'speech_not_available': 'इस डिवाइस पर आवाज पहचान उपलब्ध नहीं है।',
      'gemma_error': 'Gemma मॉडल तक नहीं पहुंचा जा सका। अपने PC पर Ollama चालू होने की पुष्टि करें।',
      'retry': 'पुनः प्रयास करें',
      'delete': 'हटाएं',
      'cancel': 'रद्द करें',
      'delete_confirm_title': 'टास्क हटाएं?',
      'delete_confirm_msg': 'क्या आप वाकई इस टास्क को इतिहास से हटाना चाहते हैं?',
      'saved_successfully': 'टास्क सफलतापूर्वक सेव हो गया!',
      'message_copied': 'मैसेज कॉपी हो गया!',
      'app_info': 'व्यापारमित्र AI • लोकल ऑफलाइन सहायक',
      'version': 'संस्करण 1.0.0',
    },
  };

  String translate(String key) {
    final langCode = locale.languageCode;
    return _localizedValues[langCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'gu', 'hi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
